hard to say that but it is try to refactor
Nick46368/module4 pull request #1
Opened 2021-01-10 20:26 UTC by Nick46368

2021-01-11 18:39 UTC, DenysLepekha requested changes

2021-01-11 18:39 UTC, DenysLepekha commented on Planes/experimentalPlane.js
> +    constructor(model, maxSpeed, maxFlightDistance, maxLoadCapacity, type, classificationLevel) {
Same here.

2021-01-11 18:39 UTC, DenysLepekha commented on test/airport.spec.js
>          let flag = false;
Use built-in chai assertions e.g. assert.isNotEmpty(transportMilitaryPlanes);

2021-01-11 18:39 UTC, DenysLepekha commented on test/airport.spec.js
> +describe('should test different types of planes', () => {
Message here should be a starting point for the following 'its' similarly as in removed version: describe('My Test', () => {

2021-01-11 18:39 UTC, DenysLepekha commented on test/airport.spec.js
> +        assert.isFalse( expectedPlaneWithMaxPassengersCapacity == PassengerPlane);
Passenger plane with max capacity should be checked here.

2021-01-11 18:39 UTC, DenysLepekha commented on test/airport.spec.js
> +    it('should sort passenger plane with max load capacity', () => {
Compare instance of PassengerPlane class with expected data and use chai built-in asseretions.

2021-01-11 18:39 UTC, DenysLepekha commented on test/airport.spec.js
> +    it('should test that has at least one bomber in military planes', () => {
Use chai built-in assertions. Array isn't empty can be checked here.

2021-01-11 18:39 UTC, DenysLepekha commented on test/airport.spec.js
> +    it('should check that experimental planes has classification level higher than unclassified', () => {
Check and fix this test.

2021-01-12 12:03 UTC, Nick46368 commented on Airport/Airport.js
> +    getTransportMilitaryPlane() {
from 3 to 1

2021-01-12 12:29 UTC, Nick46368 commented on test/airport.spec.js
> +describe('should test different types of planes', () => {
return 'My test' as starting point

2021-01-12 12:32 UTC, Nick46368 commented on test/airport.spec.js
> +        assert.isFalse( expectedPlaneWithMaxPassengersCapacity == PassengerPlane);
isEqual =

2021-01-12 12:41 UTC, Nick46368 commented on test/airport.spec.js
> +    it('should sort passenger plane with max load capacity', () => {
take first object of array with max load capacity and compare it

2021-01-14 09:07 UTC, DenysLepekha requested changes

2021-01-14 09:07 UTC, DenysLepekha commented on test/airport.spec.js
> +        assert.deepEqual(planesSortedByMaxLoadCapacity, planes.sort((a, b)  => (a['maxLoadCapacity'] > b['maxLoadCapacity'] ? 1 : -1)));
Here you compare the logic from the same methods. Take first and last planes from planesSortedByMaxLoadCapacity variable and compare it with objects which contain test data that you expect.

2021-01-14 16:38 UTC, DenysLepekha approved these changes

2021-01-14 16:41 UTC, merged